name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  op:
    required: true
    description: "Operation to perform (encode or decode)"
    default: "encode"
  in:
    required: true
    description: "Input data"
  secret:
    required: true
    description: "Secret to encrypt/decrypt data"
outputs:
  out:
    description: "Result of encryption/decryption"
    value: "${{ steps.context.outputs.action-result }}"
runs:
  using: "composite"
  steps:
    - uses: olafurpg/setup-gpg@v3
    - id: code
      shell: bash
      run: |
        case "${{ inputs.op }}" in
          encode)
            result=$(gpg --symmetric --batch --passphrase "${{ inputs.secret }}" --output - <(echo "${{ inputs.in }}") | base64 -w0)
            echo "out=${result}" >> $GITHUB_OUTPUT
            ;;
           
          decode)
            result=$(gpg --decrypt --quiet --batch --passphrase "${{ inputs.secret }}" --output - <(echo "${{ inputs.in }}" | base64 --decode))
            echo "out=${result}" >> $GITHUB_OUTPUT            
            ;;
           
          *)
            echo $"op input can be only {encode|decode}"
            exit 1  
        esac
