name: 'Secret output'
description: 'Allow outputs that contains secrets to be passed between jobs by encrypting them.'
author: hello@cloudposse.com
branding:
  icon: 'shield'
  color: 'white'
inputs:
  op:
    required: true
    description: "Operation to perform (encode or decode)"
    default: "encode"
  in:
    required: true
    description: "Input data"
  secret:
    required: true
    description: "Secret to encrypt/decrypt data"
outputs:
  out:
    description: "Result of encryption/decryption"
runs:
  using: "composite"
  steps:
    - id: settings
      shell: bash
      env:
        OPERATION: ${{ inputs.op }}
        IN: ${{ inputs.in }}
        SECRET: ${{ inputs.secret }}
      run: |
        set -e
  
        case "${OPERATION}" in
          encode)
            result=$(gpg --symmetric --batch --passphrase "${SECRET}" --output - <(echo "${IN}") | base64 -w0)
            echo "out=${result}" >> $GITHUB_OUTPUT
          ;;
        
          decode)
            result=$(gpg --decrypt --quiet --batch --passphrase "${SECRET}" --output - <(echo "${IN}" | base64 -d))
            echo "::add-mask::${result}"
            echo "out=${result}" >> $GITHUB_OUTPUT
          ;;
        
        *)
        echo $"op input can be only {encode|decode}"
        exit 1
        esac
