name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  op:
    required: true
    description: "Operation to perform (encode or decode)"
    default: "encode"
  in:
    required: true
    description: "Input data"
  secret:
    required: true
    description: "Secret to encrypt/decrypt data"
outputs:
  out:
    description: "Result of encryption/decryption"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPERATION: ${{ inputs.op }}
    IN: ${{ inputs.in }}
    SECRET: ${{ inputs.secret }}
