name: Test example positive
on:
#  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
#  #
#  # Added pull_request to register workflow from the PR.
#  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
#  pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

    outputs:
      secret: test123

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: masked
        run: |
          echo '::add-mask::test'
          echo This is a test
          echo "masked-result=test" >> $GITHUB_OUTPUT
          echo "non-masked-result=example" >> $GITHUB_OUTPUT

      - uses: ./
        id: current
        with:
          secret: ${{ steps.setup.outputs.secret }}
          do: encode
          in: ${{ needs.test.outputs.masked-result }}

    outputs:
      result: "${{ steps.current.outputs.out }}"

  assert:
    runs-on: ubuntu-latest
    needs: [setup, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./
        id: masked-result
        with:
          secret: ${{ steps.setup.outputs.secret }}
          do: decode
          in: ${{ needs.test.outputs.result }}

      - uses: nick-fields/assert-action@v1
        with:
          expected: 'test'
          actual: "${{ steps.test.masked-result.out }}"

      - uses: nick-fields/assert-action@v1
        with:
          expected: 'true'
          actual: "${{ needs.test.outputs.result }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
